[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "zkwasmsdk"
version = "0.1.0"
description = "TODO"
readme = "README.md"
authors = [{ name = "Arriviste", email = "1900017707@pku.edu.cn" }]
dependencies = [
    "requests>=2.25.1",
]